#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "merle"
require "merle/cli"

Merle::CLI.start(ARGV)
